### ISSUE TITLE
LogPub tests fail while core is running

### ISSUE THREAD

**Issue by schwabe** [fp7-netide/Engine#108]
I often compile/install the core while karaf is running to update the module. Unfortenately the logpub tests fail when doing this

``````
[main] INFO eu.netide.core.logpub.LogPub - LogPub Constructor.
[main] INFO eu.netide.core.logpub.LogPub - LogPub Start().
[LogPub Receive Loop] INFO eu.netide.core.logpub.LogPub - LogPub started.
Exception in thread "LogPub Receive Loop" org.zeromq.ZMQException: Errno 48 : Address already in use
    at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:1344)
    at org.zeromq.ZMQ$Socket.bind(ZMQ.java:1116)
    at org.zeromq.ZMQ$Socket.bind(ZMQ.java:1080)
    at eu.netide.core.logpub.LogPub.run(LogPub.java:72)
    at java.lang.Thread.run(Thread.java:745)
Message from backend test```
``````

**Comment by amarsico** [comment]
Hi @schwabe, I think you can do nothing about it... If you are running Karaf and the Core inside it, the socket will be always in use, since ZMQ is already running.

**Comment by KevinPhemius** [comment]
Yes @amarsico is right.

**Comment by KevinPhemius** [comment]
I can add a catch if the address is already in use.
