### ISSUE TITLE
Core does not support the new netip library

### ISSUE THREAD

**Issue by sergiotamu** [fp7-netide/Engine#118]
Hello @schwabe  and @doriguzzi,

I have pulled the last version of the code and there is a new version of the netip.py library. However, the core does not support that new version and It outputs the next error:

```
2016-09-12 14:29:09,758 | ERROR | tor Receive Loop | ShimManager                      | 145 - core.connectivity - 1.1.0.SNAPSHOT | Unable to parse received data from 'shim' ([5, 17, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 8, 0, 0, 0, 0]).
java.lang.IllegalArgumentException: Unexpected value 5
    at eu.netide.lib.netip.NetIDEProtocolVersion.parse(NetIDEProtocolVersion.java:56)[143:netip:1.1.0.SNAPSHOT]
    at eu.netide.lib.netip.NetIPConverter.parseHeader(NetIPConverter.java:42)[143:netip:1.1.0.SNAPSHOT]
    at eu.netide.lib.netip.NetIPConverter.parseRawMessage(NetIPConverter.java:29)[143:netip:1.1.0.SNAPSHOT]
    at eu.netide.lib.netip.NetIPConverter.parseConcreteMessage(NetIPConverter.java:18)[143:netip:1.1.0.SNAPSHOT]
    at eu.netide.core.connectivity.ShimManager.OnDataReceived(ShimManager.java:64)[145:core.connectivity:1.1.0.SNAPSHOT]
    at eu.netide.core.connectivity.ZeroMQBasedConnector.run(ZeroMQBasedConnector.java:110)[145:core.connectivity:1.1.0.SNAPSHOT]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
```

Thanks!
Sergio

**Comment by doriguzzi** [comment]
Yes, sorry for this. Arne, could you please update the Java netip library with version 0x5? 
As I wrote in the email, I'm not going to change the library spec anymore. I promise ;).

Thank

--rob
