### ISSUE TITLE
Problems with incompatibility issues between ryu and mininet 

### ISSUE THREAD

**Issue by JohnPaulCosmas** [fp7-netide/Engine#149]
when running mininet with ryu remote controller I always get the following:
i@raspberrypi:/home $ ryu-manager --version
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 6, in <module>
    from ryu.cmd.manager import main
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 33, in <module>
    from ryu.app import wsgi
  File "/usr/local/lib/python2.7/dist-packages/ryu/app/wsgi.py", line 23, in <module>
    from tinyrpc.server import RPCServer
  File "/usr/local/lib/python2.7/dist-packages/tinyrpc/__init__.py", line 4, in <module>
    from .protocols import *
  File "/usr/local/lib/python2.7/dist-packages/tinyrpc/protocols/__init__.py", line 15
    def __init__(self) -> None:
                       ^
SyntaxError: invalid syntax

How can I get a ryu version 4.34 that is compatible with the mininet version 2.2.2 that I am using?

**Comment by ElisaRojas** [comment]
Hi @JohnPaulCosmas ,
Sorry for the delay. At this point, you might have already figured it out, but this problem is directly related with the tinyrpc and eventlet libraries, as Ryu requires some specific versions of these libraries to work. In particular, you should do the following:

```
pip uninstall tinyrpc
pip install tinyrpc==0.8

pip uninstall eventlet
pip install eventlet==0.30.2
```

If you just reinstall tinyrpc, you might have another (different) problem with eventlet, so that is why I have also included a reinstallation for eventlet (even if this does not appear in your current log). You can try to execute one first, and then the other, or both together :)

I hope it helps!
