### ISSUE TITLE
Bundle stuck in stopped state after exception

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#22]
Hello,

I tried to test the core with the small python client.
It doesn't work because the message is to simple, we need the whole NetIDE API header for the lib.netip to parse it.
So it obviously throws an error when sending a "basic" message such as ['shim','test']:

<pre>
Exception in thread "ZeroMQBasedConnector Receive Loop" java.lang.IllegalArgumentException: Unexpected value 48
    at eu.netide.lib.netip.NetIDEProtocolVersion.parse(NetIDEProtocolVersion.java:48)
    at eu.netide.lib.netip.NetIPConverter.parseHeader(NetIPConverter.java:42)
    at eu.netide.lib.netip.NetIPConverter.parseRawMessage(NetIPConverter.java:29)
    at eu.netide.lib.netip.NetIPConverter.parseConcreteMessage(NetIPConverter.java:18)
    at eu.netide.core.connectivity.ShimManager.OnDataReceived(ShimManager.java:42)
    at eu.netide.core.connectivity.ZeroMQBasedConnector.run(ZeroMQBasedConnector.java:106)
    at java.lang.Thread.run(Thread.java:745)
</pre>

But:
- Something breaks when the exception is thrown, I don't know if it's the ZeroMQBasedConnector thread or somewhere else, but nothing can be sent anymore.
- When I try to reload the module, it throws an error because the old module is still running:

<pre>
karaf@root()> restart 132 
Exception in thread "ZeroMQBasedConnector Receive Loop" org.zeromq.ZMQException: Errno 48 : Address already in use
    at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:1344)
    at org.zeromq.ZMQ$Socket.bind(ZMQ.java:1116)
    at org.zeromq.ZMQ$Socket.bind(ZMQ.java:1080)
    at eu.netide.core.connectivity.ZeroMQBasedConnector.run(ZeroMQBasedConnector.java:88)
    at java.lang.Thread.run(Thread.java:745)
</pre>

The module block completely _karaf_ and is stuck in the _stopping_ state even if I try to shutdown _karaf_ or uninstall the features:

<pre>
karaf@root()> list
START LEVEL 100 , List Threshold: 50
 ID | State    | Lvl | Version | Name
---------------------------------------------------------
138 | Active |  80 | 1.0.0.0 | core.api Bundle
139 | Active |  80 | 1.0.0.0 | core.caos Bundle
140 | Stopping |  80 | 1.0.0.0 | core.connectivity Bundle
141 | Active |  80 | 1.0.0.0 | core.logpub Bundle
142 | Active |  80 | 1.0.0.0 | core.management Bundle
143 | Active   |  80 | 1.0.0.0 | netip Bundle
</pre>

I still can use karaf but I have to kill -9 karaf to get out of it (because the shutdown command waits for the bundle to completely stop before exiting).

Any idea?

Best,

Kévin

**Comment by TimVinkemeier** [comment]
I will look into that :wink:

**Comment by TimVinkemeier** [comment]
Okay, that was caused by an unhandled exception in message parsing. I fixed that in a329d07 and d6a1377. It will now write an error into the log and stop processing the message.
