### ISSUE TITLE
ryu-shim not working (branch ryu-protocol-1.1)

### ISSUE THREAD

**Issue by schwabe** [fp7-netide/Engine#45]
``` ryu-manager ryu-shim.py
loading app ryu-shim.py
loading app ryu.controller.ofp_handler
instantiating app ryu-shim.py of RYUShim
Connecting to Core on localhost:5555...
instantiating app ryu.controller.ofp_handler of OFPHandler
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ryu/lib/hub.py", line 52, in _launch
    func(_args, *_kwargs)
  File "/Users/arne/software/netide-engine/ryu-shim/ryu-shim.py", line 231, in _event_loop
    if type in async_messages:
NameError: global name 'async_messages' is not defined

```
```

**Comment by doriguzzi** [comment]
I forgot to push the new version of the netip library where I moved the async_messages set. Just do a pull and put the netip.py inside /usr/local/lib/python2.7/dist-packages/ryu/netide.
I will create a pip package next time....
