### ISSUE TITLE
Core connectivity not building

### ISSUE THREAD

**Issue by kjrrp** [fp7-netide/Engine#46]
Hi,

I can't seem to build the bundle Core.connectivity.

<pre>
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/Work/NetIDE/git/Engine/core/core.connectivity/src/main/java/eu/netid
  symbol:   class ModuleAnnouncementMessage
  location: class eu.netide.core.connectivity.BackendManager
[ERROR] /D:/Work/NetIDE/git/Engine/core/core.connectivity/src/main/java/eu/netid
  symbol:   class ModuleAnnouncementMessage
  location: class eu.netide.core.connectivity.BackendManager
[ERROR] /D:/Work/NetIDE/git/Engine/core/core.connectivity/src/main/java/eu/netid
  symbol:   class ModuleAnnouncementMessage
  location: class eu.netide.core.connectivity.BackendManager
[ERROR] /D:/Work/NetIDE/git/Engine/core/core.connectivity/src/main/java/eu/netid
  symbol:   class ModuleAcknowledgeMessage
  location: class eu.netide.core.connectivity.BackendManager
[ERROR] /D:/Work/NetIDE/git/Engine/core/core.connectivity/src/main/java/eu/netid
  symbol:   class ModuleAcknowledgeMessage
  location: class eu.netide.core.connectivity.BackendManager
[ERROR] /D:/Work/NetIDE/git/Engine/core/core.connectivity/src/main/java/eu/netid
  symbol:   variable MODULE_ACKNOWLEDGE
  location: class eu.netide.lib.netip.MessageType
[INFO] 6 errors
</pre>

Also the bundle Core.caos cannot pass the unit tests.

<pre>
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: TestNG652Configurator
17:20:50.439 [main] INFO  e.n.core.caos.CompositionManager - BackendManager set.
17:20:51.200 [main] INFO  e.n.core.caos.CompositionManager - Accepted new Compos
<CompositionSpecification  xmlns="http://netide.eu/schemas/compositionspecificat
  <Modules>
    <Module id="fw" loaderIdentification="ryu-fw.py"/>
  </Modules>
  <Composition>
        <ModuleCall module="fw"/>
  </Composition>
</CompositionSpecification>'.
17:20:51.207 [main] INFO  e.n.core.caos.CompositionManager - Set composition fin
17:20:51.208 [pool-1-thread-1] INFO  e.n.core.caos.CompositionManager - Waiting
17:20:51.233 [pool-1-thread-1] INFO  e.n.core.caos.CompositionManager - All requ
17:20:52.209 [main] INFO  e.n.core.caos.CompositionManager - CompositionManager
17:20:52.241 [main] ERROR e.n.core.caos.CompositionManager - An exception occurr
java.lang.NullPointerException: null
        at eu.netide.core.caos.execution.SequentialFlowExecutor.executeFlow(Sequ
        at eu.netide.core.caos.CompositionManager.OnShimMessage(CompositionManag
        at CompositionManagerTest.TestSingleNodeComposition(CompositionManagerTe
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocat
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:659) [testng-6.
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845) [testn
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153) [tes
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWork
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108) [
        at org.testng.TestRunner.privateRun(TestRunner.java:771) [testng-6.9.4.j
        at org.testng.TestRunner.run(TestRunner.java:621) [testng-6.9.4.jar:na]
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:357) [testng-6.9.4.ja
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352) [testng-
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310) [testng-6.9.4
        at org.testng.SuiteRunner.run(SuiteRunner.java:259) [testng-6.9.4.jar:na
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [tes
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199) [testng-6.9
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1124) [testng-6.9.4.ja
        at org.testng.TestNG.run(TestNG.java:1032) [testng-6.9.4.jar:na]
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.ja
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMult
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(Tes
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
17:20:52.371 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.412 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new r
17:20:52.416 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.417 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new r
17:20:52.418 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.479 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.486 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new c
17:20:52.487 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.489 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new r
17:20:52.489 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.492 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.495 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new c
17:20:52.495 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.497 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.500 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.503 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.519 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new c
17:20:52.519 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.522 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.529 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new c
17:20:52.530 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.532 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.539 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new r
17:20:52.541 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.545 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.547 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.550 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.560 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.563 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.565 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new r
17:20:52.569 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.572 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.574 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new c
17:20:52.574 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.576 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.577 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new r
17:20:52.578 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.579 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.581 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.587 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.594 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.616 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.617 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new r
17:20:52.618 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.623 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.626 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new c
17:20:52.627 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.629 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Introduced new r
17:20:52.629 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
17:20:52.630 [main] INFO  e.n.c.c.r.DefaultOFConflictResolver - Resolving in rou
Tests run: 12, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 7.467 sec <<< F
ThreeEqualRulesTest(DefaultOFConflictResolverTest)  Time elapsed: 0.187 sec  <<<
java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertTrue(Assert.java:42)
        at org.testng.Assert.assertTrue(Assert.java:52)
        at DefaultOFConflictResolverTest.ThreeEqualRulesTest(DefaultOFConflictRe

ThreeOverlappingRulesTest(DefaultOFConflictResolverTest)  Time elapsed: 0.151 se
java.lang.AssertionError: expected [REPLACED_AUTO] but found [null]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:116)
        at org.testng.Assert.assertEquals(Assert.java:167)
        at DefaultOFConflictResolverTest.ThreeOverlappingRulesTest(DefaultOFConf

TwoEqualRulesTest(DefaultOFConflictResolverTest)  Time elapsed: 0.006 sec  <<< F
java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertTrue(Assert.java:42)
        at org.testng.Assert.assertTrue(Assert.java:52)
        at DefaultOFConflictResolverTest.TwoEqualRulesTest(DefaultOFConflictReso

TwoOverlappingRulesTest(DefaultOFConflictResolverTest)  Time elapsed: 0.011 sec
java.lang.AssertionError: expected [REPLACED_AUTO] but found [null]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:116)
        at org.testng.Assert.assertEquals(Assert.java:167)
        at DefaultOFConflictResolverTest.TwoOverlappingRulesTest(DefaultOFConfli

Results :

Failed tests:
  DefaultOFConflictResolverTest.ThreeEqualRulesTest:209 expected [true] but foun
  DefaultOFConflictResolverTest.ThreeOverlappingRulesTest:282 expected [REPLACED
  DefaultOFConflictResolverTest.TwoEqualRulesTest:167 expected [true] but found
  DefaultOFConflictResolverTest.TwoOverlappingRulesTest:241 expected [REPLACED_A

Tests run: 12, Failures: 4, Errors: 0, Skipped: 0

</pre>

Best,

---

Kévin

**Comment by schwabe** [comment]
You might have an old version of library in your local maven repo. Can you try to reinstall that? (mvn clean install)

**Comment by ElisaRojas** [comment]
Hi @KevinPhemius , how are you compiling it? I've done it today in Ubuntu 14.04 without problems and two days ago I did it with Windows+IntellijIDEA and everything was ok as well. I guess you're following the Readme.md file and have everything updated?

**Comment by KevinPhemius** [comment]
"You might have an old version of library in your local maven repo. Can you try to reinstall that? (mvn clean install)"

Yep, that was it.
Thanks.

---

Kévin
