### ISSUE TITLE
Exception in backend

### ISSUE THREAD

**Issue by schwabe** [fp7-netide/Engine#50]
I am running with PAKET_IN rules installed in OpenVSwitch prior to starting ryu-shim and ryu-backend. And doing this I get the following error when starting the ryu-backend"

```
ryu-manager --ofp-tcp-listen-port 7733 ryu-backend.py tests/simple_switch.py
loading app ryu-backend.py
loading app tests/simple_switch.py
loading app ryu.controller.ofp_handler
instantiating app tests/simple_switch.py of SimpleSwitch
instantiating app ryu-backend.py of RYUClient
Backend supported protocols: {17: [1, 3, 4], 18: []}
RYU Client initiated
Connecting to Core on 127.0.0.1:5555...
instantiating app ryu.controller.ofp_handler of OFPHandler
Received ack from Core: ['', '\x02\x05\x00\x11\x00\x00\x00\x00\x00\x00\x01\x98\x00\x00\x00\x00\x00\x00\x00\x00backend-ryu-59318']
Received ack from Core: ['', '\x02\x05\x00\x0c\x00\x00\x00\x00\x00\x00\x03\xc9\x00\x00\x00\x00\x00\x00\x00\x00SimpleSwitch']
Starting the handshake process...
Waiting for the Handshake to be completed...
Handshake done!!!
Message header: (2, 17, 32, 0, 0, 1)
Message body: 04:06:00:20:00:00:01:98:00:00:00:00:00:00:00:01:00:00:01:00:fe:00:00:00:00:00:00:4f:00:00:00:00
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/arne/software/netide-engine/ryu-backend/ryu-backend.py", line 209, in run
    self.handle_read(msg)
  File "/Users/arne/software/netide-engine/ryu-backend/ryu-backend.py", line 343, in handle_read
    self.of_datapath.handle_event(decoded_header, message_data)
  File "/Users/arne/software/netide-engine/ryu-backend/ryu-backend.py", line 157, in handle_event
    handler(ev)
  File "/usr/local/lib/python2.7/site-packages/ryu/controller/ofp_handler.py", line 205, in switch_features_handler
    datapath.ports = msg.ports
AttributeError: 'OFPSwitchFeatures' object has no attribute 'ports'
```

**Comment by ElisaRojas** [comment]
Maybe this question is too obvious and you've already checked, but what OF version are you using? It seems like the 'ports' attribute (present in OF1.0 but not in OF1.3, afaik) is missing. See the backend and shim are currently implemented for OF1.0 ( @doriguzzi correct me if I'm wrong).
A similar thing applies to issue #49.

**Comment by doriguzzi** [comment]
Hi guys,

Ryu shim and backend are OF version agnostic (more or less), but it would be nice if when reporting errors the whole testing configuration was described.
I've already tested both shim and backend with OF1.0 and OF1.2. I'm not in the office today, I will test OF1.3 as soon as possible.

--rob
