### ISSUE TITLE
Impossible to connect switches to floodlight

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#6]
Hi, 

I followed the tutorial to launch the fl-odl layer with POX.

I can : 
* Build and launch floodlight
* Build and lauch POX
* Launch mininet

POX can see the new switches connecting but floodlight return this error : 
<pre>
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:384)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:354)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:276)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
</pre>

One error for each switch trying to connect.

Also on shutdown, I have various errors (supposedly due to switch/ports being down but trying to be accessed, this is secondary, the main issue is on startup).

**Comment by KevinPhemius** [comment]
The issue is not in the source code but in a library. 
I can't debug it.

**Comment by KevinPhemius** [comment]
When receiving a message, an exception (haven't found it yet) cause the switch channel to close, meaning that when the module tries to write the the (now closed) channel, the _java.net.ConnectException: Connection refused_ exception occurs.

**Comment by antonis-m** [comment]
Hi,

Apparently the problem is simpler than that. It's just that in the documentation it is stated that in the floodlightdefault.properties file the user should use 7733 as the openflow port number whereas in the code the port number that is used is 6634. Therefore it is impossible for a connection to be initiated.  The documentation for the demo shall be improved asap.

**Comment by KevinPhemius** [comment]
Hello @antonis-m ,
nice catch.

The switch can now connect to FL through POX but I can't manage any traffic.
The ping (and the ARP) are flooded to all interfaces :

<pre>
"outport":65531,"
</pre> 

I though that it was because both _Hub_ and _Forwarding_ are enabled in the config (they shouldn't, you can't have 2 modules doing traffic handling), so I deactivated _Hub_. Still not working.
