### ISSUE TITLE
Problems deploying the karaf core.

### ISSUE THREAD

**Issue by pablomuri** [fp7-netide/Engine#68]
Hi everyone,

I'm trying to deploy the karaf core but I'm having some issues. 

Following the manual: 

> Install the netide-core feature by first adding the feature repository file via feature:repo-add mvn:eu.netide.core/core/1.0.0.0-SNAPSHOT/xml/features and then running feature:install netide-core.
> The output shold indicate that the core is waiting for the shim to connect.

When I do that, te command "feature:install netide-core" doesn't show any output. Also when a try to run a "netide:" command (e.g. netide:netide:listmodules), karaf shows "Command not found".

I'm using karaf 3.0.3 and java8

```
karaf@root()> bundle:list
START LEVEL 100 , List Threshold: 50
ID | State  | Lvl | Version          | Name                    
---------------------------------------------------------------
64 | Active |  70 | 1.0.0.0-SNAPSHOT | NetIP Library           
65 | Active |  70 | 1.0.0.0-SNAPSHOT | core.api Bundle         
66 | Active |  80 | 1.0.0.0-SNAPSHOT | core.connectivity Bundle
67 | Active |  80 | 1.0.0.0-SNAPSHOT | core.caos Bundle        
68 | Active |  80 | 1.0.0.0-SNAPSHOT | core.logpub Bundle      
69 | Active |  80 | 1.0.0.0-SNAPSHOT | core.management Bundle  
```

Thanks

**Comment by schwabe** [comment]
can you check log:tail? Also the current master has some problem to install (bug #67), c3a4e82 is currently the latest version without these breaking changes.

**Comment by pablomuri** [comment]
Hello schwabe and thanks for your answer,

This is the log

```
2016-02-15 11:42:35,950 | INFO  | pool-9-thread-1  | CompositionManager               | 67 - core.caos - 1.0.0.0-SNAPSHOT | 20 seconds remaining for 1 module(s) to connect...
2016-02-15 11:42:55,953 | INFO  | pool-9-thread-1  | CompositionManager               | 67 - core.caos - 1.0.0.0-SNAPSHOT | 10 seconds remaining for 1 module(s) to connect...
2016-02-15 11:43:15,956 | INFO  | pool-9-thread-1  | CompositionManager               | 67 - core.caos - 1.0.0.0-SNAPSHOT | 0 seconds remaining for 1 module(s) to connect...
2016-02-15 11:43:15,958 | ERROR | pool-9-thread-1  | CompositionManager               | 67 - core.caos - 1.0.0.0-SNAPSHOT | Reconfiguration unsuccessful: timed out with 1 unconnected modules.
java.util.concurrent.TimeoutException: Required modules did not connect.
    at eu.netide.core.caos.CompositionManager.lambda$ReconfigureAsync$2(CompositionManager.java:89)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_72]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_72]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_72]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_72]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_72]

```

Also I tried to run the composition using the emultaor.

Thanks

**Comment by schwabe** [comment]
Yes, the core waits for the backend modules to connect. You can show the connected modules with netide:listmodules.

I haven't use the emulator in a long time. I do more unit tests and real backend so I have no idea on the status of the emulator.

**Comment by pablomuri** [comment]
The problem was that I couldn't use the netide commands in karaf. The manual says that have to use the CoreImplementation branch. I think that it is the problem. 

I've just compiled using the master branch and now karaf (and netide commands) looks work fine.

Thank you.
