### ISSUE TITLE
ZeroMQ throws Exception in the core

### ISSUE THREAD

**Issue by cstritzke** [fp7-netide/Engine#81]
I'm getting an exception in the core right after it starts. Here it is:

```
Exception in thread "ZeroMQBasedConnector Receive Loop" java.lang.NoClassDefFoundError: org/jboss/netty/buffer/ChannelBuffer
        at eu.netide.lib.netip.NetIPConverter.parseConcreteMessage(NetIPConverter.java:18)
        at eu.netide.core.connectivity.BackendManager.OnDataReceived(BackendManager.java:213)
        at eu.netide.core.connectivity.ZeroMQBasedConnector.run(ZeroMQBasedConnector.java:113)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.buffer.ChannelBuffer not found by netip [68]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
        at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 4 more
```

Consequently, no backend connects and netide:listmodules only shows the following:

```
   Id                 Name              Backend Last message (s ago)
    -                 shim                    -                    - 
```

**Comment by ElisaRojas** [comment]
Hi Christian,

Have you updated the code and the libraries? Do you still have the same issue?
@ralvarep was testing the core few days ago and didn't have these problems... 
Please share more info (commit you're using, etc) so that we can check it.

**Comment by ElisaRojas** [comment]
Hi @cstritzke , we've been testing and with the last updates @ralvarep does not have any issue anymore... Do you still have it?

**Comment by cstritzke** [comment]
@ElisaRojas, it seems to work now. The master branch version works (aside from an ArrayOutOfBoundsException during the installation) fine with my client apps. The only thing I'm missing are logpub messages.

**Comment by ElisaRojas** [comment]
Yes, we also have the ArrayOutOfBoundsException during installation, but this is fixed, so we might want to close the issue :)
About the logpub messages, let's talk on Monday's telco, because we are also having some issues there :)

**Comment by cstritzke** [comment]
Agreed. I'll close it.
