### ISSUE TITLE
Core installation yields error

### ISSUE THREAD

**Issue by cstritzke** [fp7-netide/Engine#82]
I did the following:
- Set up a new VM
- Installed Java 8 and Maven 3
- cd Engine/core; mvn clean install -Dgpg.skip=true
- Downloaded karaf 3.0.5
- feature:repo-add mvn:eu.netide.core/core.features/1.1.0-SNAPSHOT/xml/features
- feature:install core

This is what happens:

```
java.lang.ArrayIndexOutOfBoundsException: 42752
    at aQute.bnd.osgi.Clazz.classConstRef(Clazz.java:1862)
    at aQute.bnd.osgi.Clazz.crawl(Clazz.java:1174)
    at aQute.bnd.osgi.Clazz.doCode(Clazz.java:1134)
    at aQute.bnd.osgi.Clazz.doAttribute(Clazz.java:945)
    at aQute.bnd.osgi.Clazz.doAttributes(Clazz.java:910)
    at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:741)
    at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:494)
    at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:483)
    at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:473)
    at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2177)
    at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2083)
    at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:138)
    at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:616)
    at org.ops4j.pax.swissbox.bnd.BndUtils.createBundle(BndUtils.java:161)
    at org.ops4j.pax.url.wrap.internal.Connection.getInputStream(Connection.java:83)
    at java.net.URL.openStream(URL.java:1045)
    at org.apache.karaf.features.internal.BundleManager.getInputStreamForBundle(BundleManager.java:230)
    at org.apache.karaf.features.internal.BundleManager.doInstallBundleIfNeeded(BundleManager.java:96)
    at org.apache.karaf.features.internal.BundleManager.installBundleIfNeeded(BundleManager.java:90)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:581)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatureDependency(FeaturesServiceImpl.java:650)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:572)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatureDependency(FeaturesServiceImpl.java:650)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:572)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:436)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:417)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:392)
    at Proxy3712135c_984a_44be_a66e_2200bf3ed3cd.installFeature(Unknown Source)
    at org.apache.karaf.features.command.InstallFeatureCommand.doExecute(InstallFeatureCommand.java:72)
    at org.apache.karaf.features.command.FeaturesCommandSupport.doExecute(FeaturesCommandSupport.java:38)
    at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33)
    at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:39)
    at org.apache.karaf.shell.commands.basic.AbstractCommand.execute(AbstractCommand.java:33)
    at Proxy28595550_a3a8_4d9c_a78c_e45bea8a2382.execute(Unknown Source)
    at Proxy28595550_a3a8_4d9c_a78c_e45bea8a2382.execute(Unknown Source)
    at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)
    at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)
    at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)
    at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)
    at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)
    at org.apache.karaf.shell.console.impl.jline.ConsoleImpl.run(ConsoleImpl.java:210)
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1$1.run(LocalConsoleManager.java:109)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.apache.karaf.jaas.modules.JaasHelper.doAs(JaasHelper.java:57)
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1.run(LocalConsoleManager.java:102)
java.lang.ArrayIndexOutOfBoundsException
```

The feature still seems to be installed, though.

**Comment by amarsico** [comment]
Hi Christian,
I found that is a known issue of Bnd component, used to wrap the Openflowj
library. The Bnd component is part of Karaf and in the version 4.0.x it was
updated.

Best

Il lunedì 21 marzo 2016, Christian Stritzke notifications@github.com ha
scritto:

> I did the following:
> - Set up a new VM
> - Installed Java 8 and Maven 3
> - cd Engine/core; mvn clean install -Dgpg.skip=true
> - Downloaded karaf 3.0.5
> - feature:repo-add
>   mvn:eu.netide.core/core.features/1.1.0-SNAPSHOT/xml/features
> - feature:install core
> 
> This is what happens:
> 
> java.lang.ArrayIndexOutOfBoundsException: 42752
>     at aQute.bnd.osgi.Clazz.classConstRef(Clazz.java:1862)
>     at aQute.bnd.osgi.Clazz.crawl(Clazz.java:1174)
>     at aQute.bnd.osgi.Clazz.doCode(Clazz.java:1134)
>     at aQute.bnd.osgi.Clazz.doAttribute(Clazz.java:945)
>     at aQute.bnd.osgi.Clazz.doAttributes(Clazz.java:910)
>     at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:741)
>     at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:494)
>     at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:483)
>     at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:473)
>     at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2177)
>     at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2083)
>     at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:138)
>     at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:616)
>     at org.ops4j.pax.swissbox.bnd.BndUtils.createBundle(BndUtils.java:161)
>     at org.ops4j.pax.url.wrap.internal.Connection.getInputStream(Connection.java:83)
>     at java.net.URL.openStream(URL.java:1045)
>     at org.apache.karaf.features.internal.BundleManager.getInputStreamForBundle(BundleManager.java:230)
>     at org.apache.karaf.features.internal.BundleManager.doInstallBundleIfNeeded(BundleManager.java:96)
>     at org.apache.karaf.features.internal.BundleManager.installBundleIfNeeded(BundleManager.java:90)
>     at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:581)
>     at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatureDependency(FeaturesServiceImpl.java:650)
>     at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:572)
>     at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatureDependency(FeaturesServiceImpl.java:650)
>     at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:572)
>     at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:436)
>     at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:417)
>     at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:392)
>     at Proxy3712135c_984a_44be_a66e_2200bf3ed3cd.installFeature(Unknown Source)
>     at org.apache.karaf.features.command.InstallFeatureCommand.doExecute(InstallFeatureCommand.java:72)
>     at org.apache.karaf.features.command.FeaturesCommandSupport.doExecute(FeaturesCommandSupport.java:38)
>     at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33)
>     at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:39)
>     at org.apache.karaf.shell.commands.basic.AbstractCommand.execute(AbstractCommand.java:33)
>     at Proxy28595550_a3a8_4d9c_a78c_e45bea8a2382.execute(Unknown Source)
>     at Proxy28595550_a3a8_4d9c_a78c_e45bea8a2382.execute(Unknown Source)
>     at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)
>     at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)
>     at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)
>     at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
>     at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)
>     at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)
>     at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)
>     at org.apache.karaf.shell.console.impl.jline.ConsoleImpl.run(ConsoleImpl.java:210)
>     at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1$1.run(LocalConsoleManager.java:109)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at org.apache.karaf.jaas.modules.JaasHelper.doAs(JaasHelper.java:57)
>     at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1.run(LocalConsoleManager.java:102)
> java.lang.ArrayIndexOutOfBoundsException
> 
> The feature still seems to be installed, though.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/fp7-netide/Engine/issues/82

## 

---

Antonio Marsico
CREATE-NET
Future Networks Area
Junior Researcher
Via alla Cascata 56/D - 38123 Povo Trento (Italy)
e-mail: antonio.marsico@create-net.org
Tel: (+39) 0461 312464
Fax: (+39) 0461 421157
Skype: toto_120

## www.create-net.org

"Roads? Where we're going, we don't need roads"

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Any review, retransmission, dissemination or other use of, or
taking of any action in reliance upon, this information by persons or
entities other than the intended recipient is prohibited according to the
Italian Law 196/2003 of the Legislature. If you received this in error,
please contact the sender and delete the material from any computer.

Le informazioni contenute in questo messaggio di posta elettronica e nei
file allegati sono da considerarsi strettamente riservate. Il loro utilizzo
e' consentito esclusivamente al destinatario del messaggio, per le
finalita' indicate nel messaggio stesso. Qualora riceveste questo messaggio
senza esserne il destinatario, Vi preghiamo cortesemente di darcene notizia
via e-mail e di procedere alla cancellazione del messaggio stesso dal
Vostro sistema. Trattenere il messaggio stesso, divulgarlo anche in parte,
distribuirlo ad altri soggetti, copiarlo, od utilizzarlo per finalita'
diverse, costituisce comportamento contrario ai principi dettati dal D.
Lgs.196/2003.

**Comment by ElisaRojas** [comment]
Should we close this issue @cstritzke ?
