### ISSUE TITLE
Exception compiling NetIP library

### ISSUE THREAD

**Issue by ralvarep** [fp7-netide/Engine#84]
Hi,

I am testing the Java core (in master and netip-fix-new branch) and when I compile it I see the next exception related to NetIP library:

```
.....
[INFO] Building jar: /home/netide/NetIDE/Engine-mixed/libraries/netip/java/target/netip-1.1.0-SNAPSHOT-javadoc.jar
[INFO] 
[INFO] <<< maven-bundle-plugin:2.5.4:bundle (default-bundle) < package @ netip <<<
[INFO] 
[INFO] --- maven-bundle-plugin:2.5.4:bundle (default-bundle) @ netip ---
java.lang.IllegalArgumentException: Invalid syntax for version: 1.1.0-SNAPSHOT
    at aQute.bnd.version.Version.<init>(Version.java:46)
    at aQute.bnd.osgi.Analyzer.augmentExports(Analyzer.java:1711)
    at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:229)
    at aQute.bnd.osgi.Builder.analyze(Builder.java:352)
    at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:618)
    at aQute.bnd.osgi.Builder.build(Builder.java:81)
    at org.apache.felix.bundleplugin.BundlePlugin.buildOSGiBundle(BundlePlugin.java:632)
    at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:351)
    at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:268)
    at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:259)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] 
[INFO] --- maven-source-plugin:2.2.1:jar-no-fork (attach-sources) @ netip ---
[INFO] Building jar: /home/netide/NetIDE/Engine-mixed/libraries/netip/java/target/netip-1.1.0-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- maven-javadoc-plugin:2.9.1:jar (attach-javadocs) @ netip ---
[INFO] 
Loading source files for package eu.netide.lib.netip...
Constructing Javadoc information...
Standard Doclet version 1.8.0_72
Building tree for all the packages and classes...
Generating /home/netide/NetIDE/Engine-mixed/libraries/netip/java/target/apidocs/eu/netide/lib/netip/ErrorMessage.html...
.....
.....
.....
.....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.616 s
[INFO] Finished at: 2016-03-29T18:34:22+02:00
[INFO] Final Memory: 28M/69M
[INFO] ------------------------------------------------------------------------
```

Finally, it finishes successfully, but I don't know if the exception can cause some problem.
Thanks!

**Comment by amarsico** [comment]
This is a bug of `maven-bundle-plugin` [link](https://github.com/bndtools/bnd/issues/1069). I updated in #83 the plugin to version 3.0.1. Now there is no exception. Please try if everything works correctly now.

**Comment by ralvarep** [comment]
I have tested it and with your last commit in #83 now is working correctly. 
I close this issue. Thanks @amarsico !
