### ISSUE TITLE
LogPub does not start

### ISSUE THREAD

**Issue by amarsico** [fp7-netide/Engine#86]
Dear @KevinPhemius,
yesterday testing the Core I get the following error when the LogPub starts:

```
2016-04-07 13:59:54,006 | WARN  | FelixStartLevel  | BeanRecipe                       | 15 - org.apache.aries.blueprint.core - 1.4.4 | Object to be destroyed is not an instance of UnwrapperedBeanHolder, type: null
2016-04-07 13:59:54,010 | ERROR | FelixStartLevel  | BlueprintContainerImpl           | 15 - org.apache.aries.blueprint.core - 1.4.4 | Unable to start blueprint container for bundle core.logpub/1.1.0.SNAPSHOT
org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to find property descriptor pub_port on class eu.netide.core.logpub.LogPub
    at org.apache.aries.blueprint.container.BeanRecipe.getPropertyDescriptor(BeanRecipe.java:952)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BeanRecipe.setProperty(BeanRecipe.java:934)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BeanRecipe.setProperties(BeanRecipe.java:905)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BeanRecipe.setProperties(BeanRecipe.java:886)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:820)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)[15:org.apache.aries.blueprint.core:1.4.4]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_74]
    at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:247)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:183)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:682)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:377)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:269)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:294)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:263)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:253)[15:org.apache.aries.blueprint.core:1.4.4]
    at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)[9:org.apache.aries.util:1.1.1]
    at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)[9:org.apache.aries.util:1.1.1]
    at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)[9:org.apache.aries.util:1.1.1]
    at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)[9:org.apache.aries.util:1.1.1]
    at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)[9:org.apache.aries.util:1.1.1]
    at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1103)[org.apache.felix.framework-4.2.1.jar:]
    at org.apache.felix.framework.util.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:695)[org.apache.felix.framework-4.2.1.jar:]
    at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:483)[org.apache.felix.framework-4.2.1.jar:]
    at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4403)[org.apache.felix.framework-4.2.1.jar:]
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2092)[org.apache.felix.framework-4.2.1.jar:]
    at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1291)[org.apache.felix.framework-4.2.1.jar:]
    at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)[org.apache.felix.framework-4.2.1.jar:]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_74]
```

Using the command `karaf> la` I see the LogPub bundle as failure.

Best Regards

**Comment by sergiotamu** [comment]
Hello @amarsico, @KevinPhemius,

I have the same problem, maybe it could be because of the last merge @KevinPhemius did into master branch. What do you think?
This is an important issue for continue with the development of some tools!.

Best regards

**Comment by KevinPhemius** [comment]
I have the same issue.
But I can't reload the NetIDE Core with feature:install.

**Comment by KevinPhemius** [comment]
If someone who is an OSGi expert can look into this.
The LogPub loaded perfectly in the LogPubSub branch.
The port properties are indeed in the blueprint:
`
<cm:property-placeholder persistent-id="eu.netide.core.logpub" update-strategy="reload">
        <cm:default-properties>
            <cm:property name="pub_port" value="5557"/>
            <cm:property name="sub_port" value="5558"/>
        </cm:default-properties>
    </cm:property-placeholder>
`
See the core.connectivity in comparison:
`
<cm:property-placeholder persistent-id="eu.netide.core.connectivity" update-strategy="reload">
        <cm:default-properties>
            <cm:property name="port" value="5555"/>
        </cm:default-properties>
    </cm:property-placeholder>
`
The error reported is:

<pre>
2016-04-07 13:59:54,010 | ERROR | FelixStartLevel  | BlueprintContainerImpl           | 15 - org.apache.aries.blueprint.core - 1.4.4 | Unable to start blueprint container for bundle core.logpub/1.1.0.SNAPSHOT
org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to find property descriptor pub_port on class eu.netide.core.logpub.LogPub
</pre>

But the descriptor is in the class LogPub:

<pre>
    private int pub_port;
    private int sub_port;
</pre>

See core.connectivity (i ZeroMQBasedConnector.java) in comparison:

<pre>
private int port;
</pre>

I'm at loss. Anyone has any idea why the blueprint doesn't find the properties in the .java class?

---

Kévin

**Comment by ralvarep** [comment]
Related to fp7-netide/Tools#3.
