### ISSUE TITLE
Error when building core.caos

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#92]
Hi,

when I try to build the core, I have this issue with the tests of core.caos

<pre>
13:23:16.806 [main] ERROR e.n.core.caos.CompositionManager - An exception occurred while handling shim message.
java.lang.NullPointerException: null
    at eu.netide.core.caos.CompositionManager.OnShimMessage(CompositionManager.java:142) ~[classes/:na]
    at eu.netide.core.caos.test.CompositionManagerTest.TestSingleNodeComposition(CompositionManagerTest.java:84) [test-classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45-internal]
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85) [testng-6.9.4.jar:na]
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:659) [testng-6.9.4.jar:na]
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845) [testng-6.9.4.jar:na]
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153) [testng-6.9.4.jar:na]
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) [testng-6.9.4.jar:na]
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108) [testng-6.9.4.jar:na]
    at org.testng.TestRunner.privateRun(TestRunner.java:771) [testng-6.9.4.jar:na]
    at org.testng.TestRunner.run(TestRunner.java:621) [testng-6.9.4.jar:na]
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:357) [testng-6.9.4.jar:na]
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352) [testng-6.9.4.jar:na]
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310) [testng-6.9.4.jar:na]
    at org.testng.SuiteRunner.run(SuiteRunner.java:259) [testng-6.9.4.jar:na]
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.9.4.jar:na]
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.9.4.jar:na]
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199) [testng-6.9.4.jar:na]
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1124) [testng-6.9.4.jar:na]
    at org.testng.TestNG.run(TestNG.java:1032) [testng-6.9.4.jar:na]
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115) [surefire-testng-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205) [surefire-testng-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108) [surefire-testng-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111) [surefire-testng-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.1.jar:2.18.1]
Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.388 sec <<< FAILURE! - in TestSuite
testMultipleFlowMods(eu.netide.core.caos.test.ScenariosTest)  Time elapsed: 0.432 sec  <<< FAILURE!
java.lang.AssertionError: expected [MyOwnMockSwitch] but found [EuqallyFakeFirewall]
    at org.testng.Assert.fail(Assert.java:94)
    at org.testng.Assert.failNotEquals(Assert.java:496)
    at org.testng.Assert.assertEquals(Assert.java:125)
    at org.testng.Assert.assertEquals(Assert.java:178)
    at org.testng.Assert.assertEquals(Assert.java:188)
    at eu.netide.core.caos.test.ScenariosTest.extractXidFromFirstMsgToBackend(ScenariosTest.java:75)
    at eu.netide.core.caos.test.ScenariosTest.testMultipleFlowMods(ScenariosTest.java:101)

Results :

Failed tests: 
  ScenariosTest.testMultipleFlowMods:101->extractXidFromFirstMsgToBackend:75 expected [MyOwnMockSwitch] but found [EuqallyFakeFirewall]

Tests run: 17, Failures: 1, Errors: 0, Skipped: 0
</pre>

it doesn't happen every time, I have to relaunch the build multiple time for the test to pass.

**Comment by ralvarep** [comment]
Hi @KevinPhemius, it happens to me sometimes too. And as you mention, if I relaunch it, it usually builds successfully.

```
Tests run: 17, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] NetIP Library ...................................... SUCCESS [  5.909 s]
[INFO] core ............................................... SUCCESS [  0.069 s]
[INFO] core.api Bundle .................................... SUCCESS [  1.306 s]
[INFO] core.connectivity Bundle ........................... SUCCESS [  3.226 s]
[INFO] core.caos Bundle ................................... FAILURE [  3.506 s]
[INFO] core.management Bundle ............................. SKIPPED
[INFO] core.logpub Bundle ................................. SKIPPED
[INFO] core.branding Bundle ............................... SKIPPED
[INFO] core.features ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.792 s
[INFO] Finished at: 2016-04-12T11:30:38+02:00
[INFO] Final Memory: 46M/577M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project core.caos: There are test failures.
```

**Comment by KevinPhemius** [comment]
Was this fixed?
